package fr.speccy.azclientapi.bukkit.handlers;

public enum PLSPConfFlag {
    ATTACK_COOLDOWN,
    HIT_AND_BLOCK,
    HIT_INDICATOR,
    LARGE_HITBOX,
    OLD_ENCHANTEMENTS,
    PISTONS_RETRACT_ENTITIES,
    PLAYER_PUSH,
    PVP_HIT_PRIORITY,
    SEE_CHUNKS,
    SERVER_SIDE_ANVIL,
    SIDEBAR_SCORES,
    SMOOTH_EXPERIENCE_BAR,
    SORT_TAB_LIST_BY_NAMES,
    SWORD_BLOCKING;
}
